name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: eventownik_test_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check commit name
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Run prettier
        run: pnpm run format:check
        if: always()

      - name: Generate Prisma Client
        run: npx prisma generate
        if: always()
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/eventownik_test_db"

      - name: Run Lint
        run: pnpm run lint
        if: always()

      - name: Check types
        run: pnpm run typecheck
        if: always()

      - name: Apply Prisma migrations
        run: npx prisma migrate deploy
        if: always()
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/eventownik_test_db"

      - name: Run tests
        run: pnpm test
        if: always()
        env:
          NODE_ENV: test
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/eventownik_test_db"

      - name: Build
        run: pnpm run build
        if: always()
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/eventownik_test_db"
